open in android studio
By being conservative in your approach with upgrades,
you have made it the worst of both worlds.
Let me be absolutely clear.
I want the latest stable versions of all the dependencies.
If things don't work, fix them as well as you can.
If this requires rewriting code, rewrite it.
use min sdk 34 so we also allow android 14 with this build
Please update all dependencies and also update all code
where necessary to adhere to best practices
do not introduce regressions
but also do not keep bad code around just because it already exists
be ruthless in cutting out unused code
please make sure the code works right every time
also please make sure the sentry telemetry logging and error reporting works
it should report all crashes and freezes

> Task :color:compileReleaseKotlin
w: file:///home/runner/work/seal/seal/color/src/main/java/io/material/hct/Cam16.kt:381:17 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of function types.
w: file:///home/runner/work/seal/seal/color/src/main/java/io/material/hct/Cam16.kt:383:17 Expected performance impact from inlining is insignificant. Inlining works best for functions with parameters of function types.
gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run_4-1781104690967.json

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkGenericReleaseAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > 4 issues were found when checking AAR metadata:

       1.  Dependency 'androidx.core:core-ktx:1.19.0' requires libraries and applications that
           depend on it to compile against version 37 or later of the
           Android APIs.

           :app is currently compiled against android-36.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 8.13.2 is 36.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 37, then update this project to use
           compileSdk of at least 37.

           Note that updating a library or application's compileSdk (which
           allows newer APIs to be used) can be done separately from updating
           targetSdk (which opts the app in to new runtime behavior) and
           minSdk (which determines which devices the app can be installed
           on).

       2.  Dependency 'androidx.core:core-ktx:1.19.0' requires Android Gradle plugin 9.1.0 or higher.

           This build currently uses Android Gradle plugin 8.13.2.

       3.  Dependency 'androidx.core:core:1.19.0' requires libraries and applications that
           depend on it to compile against version 37 or later of the
           Android APIs.

           :app is currently compiled against android-36.

           Also, the maximum recommended compile SDK version for Android Gradle
           plugin 8.13.2 is 36.

           Recommended action: Update this project's version of the Android Gradle
           plugin to one that supports 37, then update this project to use
           compileSdk of at least 37.

           Note that updating a library or application's compileSdk (which
           allows newer APIs to be used) can be done separately from updating
           targetSdk (which opts the app in to new runtime behavior) and
           minSdk (which determines which devices the app can be installed
           on).

       4.  Dependency 'androidx.core:core:1.19.0' requires Android Gradle plugin 9.1.0 or higher.

           This build currently uses Android Gradle plugin 8.13.2.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 3s
26 actionable tasks: 23 executed, 3 up-to-date
Configuration cache entry stored.
Error: Process completed with exit code 1.